    // tutorial actions

export const CREATE_TUTORIAL="CREATE_TUTORIAL";
export const CREATE_TUTORIAL_FAIL="CREATE_TUTORIAL_FAIL";
export const RETRIEVE_TUTORIAL="RETRIEVE_TUTORIAL";
export const RETRIEVE_TUTORIAL_FAIL="RETRIEVE_TUTORIAL_FAIL";
export const RETRIEVE_ONE_TUTORIAL="RETRIEVE_ONE_TUTORIAL";
export const RETRIEVE_ONE_TUTORIAL_FAIL="RETRIEVE_ONE_TUTORIAL_FAIL";
export const UPDATE_TUTORIAL="UPDATE_TUTORIAL";
export const UPDATE_TUTORIAL_FAIL="UPDATE_TUTORIAL_FAIL";
export const DELETE_TUTORIAL="DELETE_TUTORIAL";
export const DELETE_TUTORIAL_FAIL="DELETE_TUTORIAL_FAIL";
export const DELETE_ALL_TUTORIAL="DELETE_ALL_TUTORIAL";
export const DELETE_ALL_TUTORIAL_FAIL="DELETE_ALL_TUTORIAL_FAIL"

        // auth action

export const CREATE_USER="CREATE_USER"
export const CREATE_USER_FAIL="CREATE_USER_FAIL"
export const SET_CURRENT_USER="SET_CURRENT_USER"
export const SET_CURRENT_USER_FAIL="SET_CURRENT_USER_FAIL";
export const LOGOUT_USER="LOGOUT_USER"
export const DELETE_ERROR_MESSAGE="DELETE_ERROR_MESSAGE"
export const GET_PROFILE= "GET_PROFILE";
export const GET_PROFILE_FAIL= "GET_PROFILE_FAIL";
export const UPDATE_PROFILE= "UPDATE_PROFILE";
export const UPDATE_PROFILE_FAIL= "UPDATE_PROFILE_FAIL";



